# -*- coding: utf-8 -*-
"""ProjetoPrefeitura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L6FIeS89Tnm5hW1fRuU7ZwkyaltGj3Ec

PROJETO POWER BI DA PREFEITURA DE RECIFE
"""

import numpy as np
import pandas as pd
from google.colab import files

dataSet = pd.read_csv('/content/BaseGeralPrefeitura.csv', sep = ";", encoding="ISO-8859-1")

"""# **READ**"""

dataSet.head(1-2)

dataSet.isnull().sum()

"""# ***DROP***"""

dataSet = dataSet.drop(columns=["serie_codigo"])
dataSet = dataSet.drop(columns=["situacao_codigo"])
# dataSet = dataSet.drop(columns=["Nome da Origem"])

# print(dataSet[dataSet.isna().any(axis=1)])

# dataSet = dataSet.dropna()

"""# **ALTER**

### **Alterando os tipos**
"""

dataSet.dtypes

dataSet["ano"] = dataSet["ano"].astype(str)
dataSet["codigo_escola"] = pd.to_numeric(dataSet["codigo_escola"])
dataSet["escola"] = dataSet["escola"].astype(str)
dataSet["endereco_bairro"] = dataSet["endereco_bairro"].astype(str)
dataSet["endereco_logradouro"] = dataSet["endereco_logradouro"].astype(str)
dataSet["endereco_numero"] = dataSet["endereco_numero"].astype(str)
dataSet["rpa"] = dataSet["rpa"].astype(str)
dataSet["ano_ensino"] = dataSet["ano_ensino"].astype(str)
dataSet["modalidade_ensino_codigo"] = pd.to_numeric(dataSet["modalidade_ensino_codigo"])
dataSet["modalidade_ensino"] = dataSet["modalidade_ensino"].astype(str)
dataSet["turma"] = dataSet["turma"].astype(str)
dataSet["turno"] = dataSet["turno"].astype(str)
dataSet["matricula"] = pd.to_numeric(dataSet["matricula"])
dataSet["sexo"] = dataSet["sexo"].astype(str)
dataSet["situacao_nome"] = dataSet["situacao_nome"].astype(str)

"""### **Alterando valores**

alterando valor de sexo
"""

dataSet['sexo'].unique()

dataSet['sexo'] = dataSet['sexo'].replace({
    "1": "Masculino",
    "2": "Feminino",
    "3": "Feminino"
})

"""Alterando valor de modalidade_ensino

"""

dataSet['modalidade_ensino'].unique()

dataSet['modalidade_ensino'] = dataSet['modalidade_ensino'].str.strip().replace({
    "EDUCACAO JOVENS E ADULTOS": "EDUCACAO JOVENS E ADULTOS",
    "EDUCACAO  JOVENS E ADULTOS": "EDUCACAO JOVENS E ADULTOS",
    "PROJOVEM": "EDUCACAO JOVENS E ADULTOS"
})

"""Alterando endereco_numero"""

dataSet['endereco_numero'].unique()

dataSet.loc[dataSet['endereco_numero'] == "S/N", 'endereco_numero'] = "SN"

"""Alterando RPA (Região Político Administrativa)"""

dataSet['rpa'].unique()

dataSet['rpa'] = dataSet['rpa'].replace({
    "1": "CENTRO",
    "2": "NORTE",
    "3": "NOROESTE",
    "4": "OESTE",
    "5": "SUDOESTE",
    "6": "SUL"
})

"""Alterando situação_nome"""

dataSet['situacao_nome'].unique()

dataSet['situacao_nome'].value_counts()

dataSet['situacao_nome'] = dataSet['situacao_nome'].replace({
    "RETIDO": "REPROVADO",
    "RETIDO POR FALTA": "REPROVADO POR FALTA",
    "REPROV P/  FALTA": "REPROVADO POR FALTA",
    "TR DUR ANO S/INFO": "TRANSFERÊNCIA",
    "RETIDO POR IDADE": "REPROVADO",
    "RT FALTA TR P/REDE": "TR DUR ANO P/REDE",
    "RETIDO E TR P/ REDE": "TR DUR ANO P/REDE",
    "Transferência": "TRANSFERÊNCIA",
    "DESIST/DEIXOU FREQUE": "DESISTENTE",
    "DESIST REN C/ TRANSF": "TRANSFERÊNCIA",
    "RENV S/SIT FINAL DEF": "RENV NÃO DEFINIDA",
    "FREQÜENTE": "APROVADO"

})

"""# **CREATE**"""

def faixa_etaria(idade):
    if idade <= 12:
        return 'Criança'
    elif 13 <= idade <= 18:
        return 'Adolescente'
    elif 19 <= idade <= 65:
        return 'Adulto'
    else:
        return 'Idoso'

dataSet['faixa_etaria'] = dataSet['idade'].apply(faixa_etaria)

"""# **SAVE**"""

# dataSet.to_csv('/content/BaseGeralPrefeitura_tratada.csv', index=False, sep=";")

# files.download('/content/BaseGeralPrefeitura_tratada.csv')