# -*- coding: utf-8 -*-
"""Teste ProjetoPrefeitura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k6gU9oxbxBqxj3wIi8A7oXYl077pgj87

PROJETO POWER BI DA PREFEITURA DE RECIFE
"""

import numpy as np
import pandas as pd
from google.colab import files

dataSet = pd.read_csv('/content/situacaofinal2018.csv', sep=";")

"""# **READ**"""

dataSet.head(1-2)

dataSet.isnull().sum()

"""# ***DROP***"""

dataSet = dataSet.drop(columns=["serie"])

"""# **ALTER**

### **Alterando os tipos**
"""

dataSet.dtypes

dataSet["ano"] = dataSet["ano"].astype(str)
dataSet["codigo_escola"] = pd.to_numeric(dataSet["codigo_escola"])
dataSet["escola"] = dataSet["escola"].astype(str)
dataSet["endereco_bairro"] = dataSet["endereco_bairro"].astype(str)
dataSet["endereco_logradouro"] = dataSet["endereco_logradouro"].astype(str)
dataSet["endereco_numero"] = dataSet["endereco_numero"].astype(str)
dataSet["rpa"] = dataSet["rpa"].astype(str)
dataSet["ano_ensino"] = dataSet["ano_ensino"].astype(str)
dataSet["modalidade_ensino_codigo"] = pd.to_numeric(dataSet["modalidade_ensino_codigo"])
dataSet["serie_codigo"] = pd.to_numeric(dataSet["serie_codigo"], errors='coerce')
dataSet["modalidade_ensino"] = dataSet["modalidade_ensino"].astype(str)
dataSet["turma"] = dataSet["turma"].astype(str)
dataSet["turno"] = dataSet["turno"].astype(str)
dataSet["matricula"] = pd.to_numeric(dataSet["matricula"])
dataSet["sexo"] = dataSet["sexo"].astype(str)
dataSet["situacao_codigo"] = dataSet["situacao_codigo"].astype(str)
dataSet["situacao_nome"] = dataSet["situacao_nome"].astype(str)

"""### **Alterando valores**

alterando valor de sexo
"""

dataSet['sexo'].unique()

dataSet.loc[dataSet['sexo'] == "3", 'sexo'] = "2"
dataSet.loc[dataSet['sexo'] == "1", 'sexo'] = "Masculino"
dataSet.loc[dataSet['sexo'] == "2", 'sexo'] = "Feminino"

"""Alterando valor de modalidade_ensino

"""

dataSet['modalidade_ensino'].unique()

dataSet['modalidade_ensino'] = dataSet['modalidade_ensino'].str.strip().replace({
    "EDUCACAO JOVENS E ADULTOS": "EDUCACAO JOVENS E ADULTOS",
    "EDUCACAO  JOVENS E ADULTOS": "EDUCACAO JOVENS E ADULTOS",
    "PROJOVEM": "EDUCACAO JOVENS E ADULTOS"
})

"""Alterando endereco_numero"""

dataSet['endereco_numero'].unique()

dataSet.loc[dataSet['endereco_numero'] == "S/N", 'endereco_numero'] = "SN"

"""Alterando RPA (Região Político Administrativa)"""

dataSet['rpa'].unique()

dataSet['rpa'] = dataSet['rpa'].replace({
    "1": "CENTRO",
    "2": "NORTE",
    "3": "NOROESTE",
    "4": "OESTE",
    "5": "SUDOESTE",
    "6": "SUL"
})

dataSet['situacao_nome'].unique()

dataSet['situacao_nome'].value_counts()

dataSet['situacao_nome'] = dataSet['situacao_nome'].replace({
    "RETIDO": "REPROVADO",
    "RETIDO POR FALTA": "REPROVADO POR FALTA",
    "REPROV P/  FALTA": "REPROVADO POR FALTA",
    "TR DUR ANO S/INFO": "TRANSFERÊNCIA",
    "RETIDO POR IDADE": "REPROVADO",
    "RT FALTA TR P/REDE": "TR DUR ANO P/REDE",
    "RETIDO E TR P/ REDE": "TR DUR ANO P/REDE",
    "Transferência": "TRANSFERÊNCIA",
    "DESIST/DEIXOU FREQUE": "DESISTENTE",
    "DESIST REN C/ TRANSF": "TRANSFERÊNCIA",
    "RENV S/SIT FINAL DEF": "RENV NÃO DEFINIDA",
    "FREQÜENTE": "APROVADO"

})

def faixa_etaria(idade):
    if idade <= 10:
        return 'Criança'
    elif 11 <= idade <= 17:
        return 'Adolescente'
    else:
        return 'Adulto'

dataSet['faixa_etaria'] = dataSet['idade'].apply(faixa_etaria)

dataSet.head(
)



"""# **SAVE**"""

# files.download('/content/situacaofinal2018.csv')